=== infsci2560sp16/full-stack-web-project-mansouralsaleh/src/main/resources/public/uni.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com" elementFormDefault="qualified">
  <xs:element name="Universities">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="University" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="image"/>
              <xs:element name="schools">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="school" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="schoolname"/>
                          <xs:element name="majors">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="major" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:string" name="majorname"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== infsci2560sp16/full-stack-web-project-mansouralsaleh/src/main/resources/public/unixml.xml
<?xml version="1.0"?>
<Universities xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nameless-mountain-5787.herokuapp.com uni.xsd">
	<University>
		<id>1</id>
		<name>University of Pitssburgh</name>
		<image>pitt.png</image>
		<schools>
			<school>
				<schoolname>School of Information Science</schoolname>
				<majors>
					<major>
						<majorname>Information Science</majorname>
					</major>
					<major>
						<majorname>Telecomunication</majorname>
					</major>
					<major>
						<majorname>Library and Information Science</majorname>
					</major>
				</majors>
			</school>
			<school>
				<schoolname>School of Education</schoolname>
				<majors>
					<major>
						<majorname>Administrative and Policy Studies</majorname>
					</major>
					<major>
						<majorname>Health and Physical Activity</majorname>
					</major>
					<major>
						<majorname>Instruction and Learning</majorname>
					</major>
				</majors>
			</school>
			<school>
				<schoolname>School of Information Science</schoolname>
				<majors>
					<major>
						<majorname>Information Science</majorname>
					</major>
					<major>
						<majorname>Telecomunication</majorname>
					</major>
					<major>
						<majorname>Library and Information Science</majorname>
					</major>
				</majors>
			</school>
		</schools>
	</University>
	<University>
		<id>2</id>
		<name>Carnegie Mellon University</name>
		<image>cmu.jpg</image>
		<schools>
			<school>
				<schoolname>A</schoolname>
				<majors>
					<major>
						<majorname>major 1</majorname>
					</major>
					<major>
						<majorname>major 2</majorname>
					</major>
					<major>
						<majorname>major 3</majorname>
					</major>
				</majors>
			</school>
			<school>
				<schoolname>School of Education</schoolname>
				<majors>
					<major>
						<majorname>Administrative and Policy Studies</majorname>
					</major>
					<major>
						<majorname>Health and Physical Activity</majorname>
					</major>
					<major>
						<majorname>Instruction and Learning</majorname>
					</major>
				</majors>
			</school>
			<school>
				<schoolname>School of Information Science</schoolname>
				<majors>
					<major>
						<majorname>Information Science</majorname>
					</major>
					<major>
						<majorname>Telecomunication</majorname>
					</major>
					<major>
						<majorname>Library and Information Science</majorname>
					</major>
				</majors>
			</school>
		</schools>
	</University>
	<University>
		<id>3</id>
		<name>Duquesne University</name>
		<image>logo-duquesne-university.jpg</image>
		<schools>
			<school>
				<schoolname>School of Information Science</schoolname>
				<majors>
					<major>
						<majorname>Information Science</majorname>
					</major>
					<major>
						<majorname>Telecomunication</majorname>
					</major>
					<major>
						<majorname>Library and Information Science</majorname>
					</major>
				</majors>
			</school>
			<school>
				<schoolname>School of Education</schoolname>
				<majors>
					<major>
						<majorname>Administrative and Policy Studies</majorname>
					</major>
					<major>
						<majorname>Health and Physical Activity</majorname>
					</major>
					<major>
						<majorname>Instruction and Learning</majorname>
					</major>
				</majors>
			</school>
			<school>
				<schoolname>School of Information Science</schoolname>
				<majors>
					<major>
						<majorname>Information Science</majorname>
					</major>
					<major>
						<majorname>Telecomunication</majorname>
					</major>
					<major>
						<majorname>Library and Information Science</majorname>
					</major>
				</majors>
			</school>
		</schools>
	</University>
	<University>
		<id>4</id>
		<name>Robert Morris University</name>
		<image>Robert_Morris_University_logo.png</image>
		<schools>
			<school>
				<schoolname>School of Information Science</schoolname>
				<majors>
					<major>
						<majorname>Information Science</majorname>
					</major>
					<major>
						<majorname>Telecomunication</majorname>
					</major>
					<major>
						<majorname>Library and Information Science</majorname>
					</major>
				</majors>
			</school>
			<school>
				<schoolname>School of Education</schoolname>
				<majors>
					<major>
						<majorname>Administrative and Policy Studies</majorname>
					</major>
					<major>
						<majorname>Health and Physical Activity</majorname>
					</major>
					<major>
						<majorname>Instruction and Learning</majorname>
					</major>
				</majors>
			</school>
			<school>
				<schoolname>School of Information Science</schoolname>
				<majors>
					<major>
						<majorname>Information Science</majorname>
					</major>
					<major>
						<majorname>Telecomunication</majorname>
					</major>
					<major>
						<majorname>Library and Information Science</majorname>
					</major>
				</majors>
			</school>
		</schools>
	</University>
	<University>
		<id>5</id>
		<name>University Name</name>
		<image>uni.png</image>
		<schools>
			<school>
				<schoolname>School of Information Science</schoolname>
				<majors>
					<major>
						<majorname>Information Science</majorname>
					</major>
					<major>
						<majorname>Telecomunication</majorname>
					</major>
					<major>
						<majorname>Library and Information Science</majorname>
					</major>
				</majors>
			</school>
			<school>
				<schoolname>School of Education</schoolname>
				<majors>
					<major>
						<majorname>Administrative and Policy Studies</majorname>
					</major>
					<major>
						<majorname>Health and Physical Activity</majorname>
					</major>
					<major>
						<majorname>Instruction and Learning</majorname>
					</major>
				</majors>
			</school>
			<school>
				<schoolname>School of Information Science</schoolname>
				<majors>
					<major>
						<majorname>Information Science</majorname>
					</major>
					<major>
						<majorname>Telecomunication</majorname>
					</major>
					<major>
						<majorname>Library and Information Science</majorname>
					</major>
				</majors>
			</school>
		</schools>
	</University>
</Universities>
